forcount: 00*8
forloops: 00*8
forloop: 00*8
for_:
    forloop > !
    forcount > TRUE + forcount<
    forcount > forloops > for_ ~
for:
    NULL forcount<
    forcount > forloops > for_ ~

msg: "Hello World "
msg_: 00*8
nl: 0a
zero: "0" 00*7
loops: 04 00*7
loop:
    write STDOUT msg msg* $
    forcount > zero > + msg_<
    write STDOUT msg_ TRUE $
    write STDOUT nl nl* $
main:
    loop forloop<
    NULL forloops<
    for !
    loops > forloops<
    for !
    exit OK $
