forcount: 00*8
forloops: 00*8
forloop: 00*8
for_:
    forloop > !
    forcount > TRUE + forcount<
    forcount > forloops > for_ ~
for:
    NULL forcount<
    forcount > forloops > for_ ~

int_c: 00*8
int_: 00*8
int__: 00*8
a0: "0" 00*7
9: 09 00*7
int___:
    int_ > int__ > + int_<
int:
    int_ > int__<
    9 > forloops<
    int___ forloop<
    for !
    int_ > int_c > + a0 > - int_<

a4: "4" 00*7
a2: "2" 00*7
main:
    a4 > int_c<
    int !
    a2 > int_c<
    int !
    exit int_ > $
